# -*- coding: utf-8 -*-
"""main_2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XS8U1-cU7d-KHmX2TebhnptKtTulFhsQ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display
from sklearn.linear_model import LinearRegression
from google.colab import drive
drive.mount('/content/drive')

# ==========================================================
# 1. CAMINHOS DOS ARQUIVOS
# ==========================================================

path_2025 = '/content/drive/MyDrive/Colab Notebooks/projeto aplicado1/Demanda de Passageiros por Estação - Média Dias Úteis - 2025_9 (1).csv'

path_2026 = '/content/drive/MyDrive/Colab Notebooks/projeto aplicado1/Demanda de Passageiros por Estação - Média Dias Úteis - 2026_0 (1).csv'
# ==========================================================
# 2. CONFIGURAÇÕES GERAIS
# ==========================================================

MESES = [
    'Jan', 'Fev', 'Mar', 'Abr',
    'Mai', 'Jun', 'Jul', 'Ago',
    'Set', 'Out', 'Nov', 'Dez'
]

sns.set_style("whitegrid")

# ==========================================================
# 3. FUNÇÃO PARA EXTRAIR E LIMPAR OS DADOS
# ==========================================================

def extrair_dados_metro(caminho_arquivo, ano_referencia):
    """
    Lê o arquivo bruto do metrô, identifica o cabeçalho correto,
    limpa linhas inválidas, associa cada estação à sua linha
    e devolve os dados em formato longo.

    Retorna:
    DataFrame com colunas:
    ['Estacao', 'Linha', 'Ano', 'Mes', 'Passageiros']
    """

    # ------------------------------------------------------
    # LEITURA DO CSV
    # ------------------------------------------------------

    df_raw = pd.read_csv(
        caminho_arquivo,
        sep=';',
        encoding='latin-1',
        header=None
    )

    # ------------------------------------------------------
    # IDENTIFICAR LINHA DO CABEÇALHO
    # ------------------------------------------------------

    try:
        indice_cabecalho = df_raw[
            df_raw.apply(
                lambda linha: linha.astype(str).str.contains(
                    'Jan|Fev|Mar|Abr',
                    case=False
                ).any(),
                axis=1
            )
        ].index[0]

    except IndexError:
        raise ValueError(
            f'Não foi possível localizar o cabeçalho no arquivo {ano_referencia}.'
        )

    # ------------------------------------------------------
    # AJUSTAR CABEÇALHO
    # ------------------------------------------------------

    df_temp = df_raw.iloc[indice_cabecalho:].copy()

    df_temp.columns = (
        df_temp.iloc[0]
        .astype(str)
        .str.strip()
    )

    df_temp = df_temp[1:].copy()

    # Renomear primeira coluna
    df_temp.rename(
        columns={df_temp.columns[0]: 'Estacao'},
        inplace=True
    )

    # ------------------------------------------------------
    # EXTRAÇÃO DAS ESTAÇÕES
    # ------------------------------------------------------

    linha_atual = None
    registros = []

    for _, row in df_temp.iterrows():

        nome_estacao = str(row['Estacao']).strip()

        if nome_estacao == '' or nome_estacao.lower() == 'nan':
            continue

        nome_maiusculo = nome_estacao.upper()

        # Detecta linha do metrô
        if 'LINHA' in nome_maiusculo:
            linha_atual = nome_estacao
            continue

        # Ignorar linhas inválidas
        if (
            nome_maiusculo in ['ESTAÇÃO', 'ESTACAO']
            or 'TOTAL' in nome_maiusculo
            or 'FONTE' in nome_maiusculo
            or 'MÉDIA' in nome_maiusculo
            or 'MEDIA' in nome_maiusculo
        ):
            continue

        if linha_atual is None:
            continue

        registro = {
            'Estacao': nome_estacao,
            'Linha': linha_atual,
            'Ano': ano_referencia
        }

        # Adicionar meses
        for mes in MESES:

            if mes in df_temp.columns:
                registro[mes] = row[mes]
            else:
                registro[mes] = np.nan

        registros.append(registro)

    # ------------------------------------------------------
    # TRANSFORMAR EM DATAFRAME
    # ------------------------------------------------------

    df_estacoes = pd.DataFrame(registros)

    # ------------------------------------------------------
    # FORMATO LONGO
    # ------------------------------------------------------

    df_long = df_estacoes.melt(
        id_vars=['Estacao', 'Linha', 'Ano'],
        value_vars=MESES,
        var_name='Mes',
        value_name='Passageiros'
    )

    # ------------------------------------------------------
    # LIMPEZA DOS VALORES
    # ------------------------------------------------------

    df_long['Passageiros'] = (
        df_long['Passageiros']
        .astype(str)
        .str.replace('.', '', regex=False)
        .str.replace(',', '.', regex=False)
        .str.strip()
    )

    df_long['Passageiros'] = pd.to_numeric(
        df_long['Passageiros'],
        errors='coerce'
    )

    # ------------------------------------------------------
    # PADRONIZAÇÃO
    # ------------------------------------------------------

    df_long['Estacao'] = (
        df_long['Estacao']
        .str.upper()
        .str.strip()
    )

    df_long['Linha'] = (
        df_long['Linha']
        .str.upper()
        .str.strip()
    )

    # Remover nulos
    df_long.dropna(subset=['Passageiros'], inplace=True)

    # Remover duplicados
    df_long.drop_duplicates(inplace=True)

    return df_long

# ==========================================================
# 4. CARREGAMENTO DAS BASES
# ==========================================================

df_2025 = extrair_dados_metro(path_2025, 2025)
df_2026 = extrair_dados_metro(path_2026, 2026)

# Consolidar
df_total = pd.concat(
    [df_2025, df_2026],
    ignore_index=True
)

# ==========================================================
# 5. VISÃO GERAL DA BASE
# ==========================================================

print('=' * 70)
print('VISÃO GERAL DA BASE TRATADA')
print('=' * 70)

print(f'Total de registros 2025: {len(df_2025)}')
print(f'Total de registros 2026: {len(df_2026)}')
print(f'Total geral: {len(df_total)}')

print(f'Quantidade de estações: {df_total["Estacao"].nunique()}')
print(f'Quantidade de linhas: {df_total["Linha"].nunique()}')

print('\nAmostra da base:')
display(df_total.head())

# ==========================================================
# 6. ESTATÍSTICA DESCRITIVA
# ==========================================================

print('=' * 70)
print('ESTATÍSTICA DESCRITIVA')
print('=' * 70)

estatistica_ano = (
    df_total
    .groupby('Ano')['Passageiros']
    .describe()
    .round(2)
)

display(estatistica_ano)

# ==========================================================
# 7. ESTAÇÕES MAIS LOTADAS
# ==========================================================

print('=' * 70)
print('TOP 10 ESTAÇÕES MAIS LOTADAS')
print('=' * 70)

top_estacoes = (
    df_total
    .groupby(['Estacao', 'Linha'])['Passageiros']
    .max()
    .reset_index()
    .sort_values(by='Passageiros', ascending=False)
)

display(top_estacoes.head(10))

# ==========================================================
# 8. RANKING DAS LINHAS
# ==========================================================

print('=' * 70)
print('RANKING DAS LINHAS MAIS MOVIMENTADAS')
print('=' * 70)

ranking_linhas = (
    df_total
    .groupby('Linha')['Passageiros']
    .mean()
    .sort_values(ascending=False)
)

display(ranking_linhas)

# ==========================================================
# 9. ESTAÇÃO MAIS LOTADA POR MÊS
# ==========================================================

print('=' * 70)
print('ESTAÇÃO MAIS LOTADA POR MÊS')
print('=' * 70)

df_estacao_mais_lotada_mes = (
    df_total
    .sort_values(
        ['Ano', 'Mes', 'Passageiros'],
        ascending=[True, True, False]
    )
    .groupby(['Ano', 'Mes'], as_index=False)
    .first()
)

display(
    df_estacao_mais_lotada_mes[
        ['Ano', 'Mes', 'Estacao', 'Linha', 'Passageiros']
    ]
)

# ==========================================================
# 10. CRESCIMENTO ENTRE ANOS
# ==========================================================

print('=' * 70)
print('CRESCIMENTO PERCENTUAL')
print('=' * 70)

media_ano = (
    df_total
    .groupby('Ano')['Passageiros']
    .mean()
)

crescimento = (
    (media_ano[2026] - media_ano[2025])
    / media_ano[2025]
) * 100

print(f'Crescimento percentual: {crescimento:.2f}%')

# ==========================================================
# 11. VARIABILIDADE DAS ESTAÇÕES
# ==========================================================

print('=' * 70)
print('ESTAÇÕES MAIS INSTÁVEIS')
print('=' * 70)

variabilidade = (
    df_total
    .groupby('Estacao')['Passageiros']
    .std()
    .sort_values(ascending=False)
)

display(variabilidade.head(10))

# ==========================================================
# 12. CONCLUSÃO AUTOMÁTICA
# ==========================================================

print('=' * 70)
print('CONCLUSÃO AUTOMÁTICA')
print('=' * 70)

estacao_critica = (
    df_total
    .groupby('Estacao')['Passageiros']
    .mean()
    .idxmax()
)

print(
    f'A estação com maior média de passageiros foi {estacao_critica}.'
)

# ==========================================================
# 13. MACHINE LEARNING - PREVISÃO
# ==========================================================

print('=' * 70)
print('PREVISÃO DE DEMANDA')
print('=' * 70)

df_ml = (
    df_total
    .groupby(['Ano', 'Mes'])['Passageiros']
    .mean()
    .reset_index()
)

df_ml['Mes_Num'] = range(len(df_ml))

X = df_ml[['Mes_Num']]
y = df_ml['Passageiros']

modelo = LinearRegression()

modelo.fit(X, y)

df_ml['Previsao'] = modelo.predict(X)

display(df_ml)

# ==========================================================
# 14. GRÁFICO - EVOLUÇÃO MENSAL
# ==========================================================

plt.figure(figsize=(14, 6))

sns.lineplot(
    data=df_total,
    x='Mes',
    y='Passageiros',
    hue='Ano',
    estimator='mean',
    marker='o'
)

plt.title('Evolução Média de Passageiros por Mês')
plt.xlabel('Mês')
plt.ylabel('Média de Passageiros')

plt.grid(True)

plt.show()

# ==========================================================
# 15. HEATMAP
# ==========================================================

pivot = df_total.pivot_table(
    values='Passageiros',
    index='Estacao',
    columns='Mes',
    aggfunc='mean'
)

plt.figure(figsize=(16, 12))

sns.heatmap(
    pivot,
    cmap='Reds'
)

plt.title('Mapa de Calor da Demanda de Passageiros')

plt.show()

# ==========================================================
# 16. GRÁFICO TOP ESTAÇÕES
# ==========================================================

plt.figure(figsize=(14, 6))

sns.barplot(
    data=top_estacoes.head(10),
    x='Passageiros',
    y='Estacao'
)

plt.title('Top 10 Estações Mais Lotadas')
plt.xlabel('Passageiros')
plt.ylabel('Estação')

plt.show()

# ==========================================================
# 17. EXPORTAÇÃO
# ==========================================================

top_estacoes.to_csv(
    'top_estacoes.csv',
    index=False,
    encoding='utf-8-sig'
)

df_estacao_mais_lotada_mes.to_csv(
    'estacao_mais_lotada_mes.csv',
    index=False,
    encoding='utf-8-sig'
)

df_ml.to_csv(
    'previsao_demanda.csv',
    index=False,
    encoding='utf-8-sig'
)

print('\nArquivos exportados com sucesso!')
print('- top_estacoes.csv')
print('- estacao_mais_lotada_mes.csv')
print('- previsao_demanda.csv')

"""# Nova seção

# Nova seção
"""